const number1 = 2;
const number2 = 4;
let product = number1 * number2;
console.log('value of product:', product);
console.log('type of product:', typeof product);
const charge = 27;
const payment = 4.5;
let amountRemaining = charge - payment;
console.log('value of amountRemaining:', amountRemaining);
console.log('type of amountRemaining:', typeof amountRemaining);
